language: c++
compiler: gcc
sudo: true
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    env: TARGET="linux"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
          - g++-4.9
          - gdb

  - os: osx
    osx_image: xcode8
    compiler: clang
    env:
      - TARGET="osx"
  exclude:
    - compiler: gcc

env:
  global:
    - OF_REPO=https://github.com/openFrameworks/openFrameworks.git
    - OF_ROOT=$TRAVIS_BUILD_DIR/openFrameworks
    - OFX_ADDONS_CI_REPO=https://github.com/bakercp/ofxAddonsCI.git
    - OFX_ADDONS_CI_ROOT=$TRAVIS_BUILD_DIR/addons-ci
    - OFX_ADDON_NAME=$( echo $TRAVIS_REPO_SLUG | sed 's/.*\/\(.*\)/\1/' )

git:
  depth: 1

# All files in the build-lifecycle
# https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle
before_install:
  - mkdir ~/$OFX_ADDON_NAME
  - mv * ~/$OFX_ADDON_NAME
  - rm -rf *
  - git clone $OF_REPO --depth=1 --branch="$TRAVIS_BRANCH" $OF_ROOT
  - git clone $OFX_ADDONS_CI_REPO --depth=1 --branch="$TRAVIS_BRANCH" $OFX_ADDONS_CI_ROOT
  - cd $OFX_ADDONS_CI_ROOT
  - git submodule update --init --recursive
  - cd $TRAVIS_BUILD_DIR
  - ls -la $TRAVIS_BUILD_DIR
  - ls -la ~/$OFX_ADDON_NAME
  - $OFX_ADDONS_CI_ROOT/before_install.sh
install:
  - $OFX_ADDONS_CI_ROOT/install.sh

before_script:
  - $OFX_ADDONS_CI_ROOT/before_script.sh
script:
  - $OFX_ADDONS_CI_ROOT/script.sh
after_script:
  - $OFX_ADDONS_CI_ROOT/after_script.sh

after_success:
  - $OFX_ADDONS_CI_ROOT/after_success.sh
after_failure:
  - $OFX_ADDONS_CI_ROOT/after_failure.sh

before_deploy:
  - $OFX_ADDONS_CI_ROOT/before_deploy.sh
# deploy:
#   - $OFX_ADDONS_CI_ROOT/deploy.sh
after_deploy:
  - $OFX_ADDONS_CI_ROOT/after_deploy.sh
