language: c++
compiler: gcc
sudo: true
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    env: TARGET="linux"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
          - g++-4.9
          - gdb

  - os: osx
    osx_image: xcode8
    compiler: clang
    env:
      - TARGET="osx"
  exclude:
    - compiler: gcc

env:
  global:
    - OF_REPO=https://github.com/openFrameworks/openFrameworks.git
    - OF_ROOT=$TRAVIS_BUILD_DIR/openFrameworks
    - OF_ADDONS=$OF_ROOT/addons
    - OFX_ADDONS_CI_REPO=https://github.com/bakercp/ofxAddonsCI.git
    - OFX_ADDONS_CI_ROOT=$TRAVIS_BUILD_DIR/addons-ci
    - OFX_ADDON_NAME=$( echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2 )

git:
  depth: 1

# All files in the build-lifecycle
# https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle
before_install:
  - $OFX_ADDONS_CI_ROOT/scripts/before_install.sh
install:
  - $OFX_ADDONS_CI_ROOT/scripts/install.sh
  - echo $TEST_VAR
before_script:
  - $OFX_ADDONS_CI_ROOT/scripts/before_script.sh
  - echo $TEST_VAR
script:
  - $OFX_ADDONS_CI_ROOT/scripts/script.sh
  - echo $TEST_VAR
after_script:
  - $OFX_ADDONS_CI_ROOT/scripts/after_script.sh
  - echo $TEST_VAR

after_success:
  - $OFX_ADDONS_CI_ROOT/scripts/after_success.sh
  - echo $TEST_VAR

after_failure:
  - $OFX_ADDONS_CI_ROOT/scripts/after_failure.sh
  - echo $TEST_VAR

before_deploy:
  - $OFX_ADDONS_CI_ROOT/scripts/before_deploy.sh
  - echo $TEST_VAR
# deploy:
#   - $OFX_ADDONS_CI_ROOT/deploy.sh
after_deploy:
  - $OFX_ADDONS_CI_ROOT/after_deploy.sh
  - echo $TEST_VAR
